// Builds src/data/replaySample.ts: a short, literal replay clip of real
// Metrica Sports tracking data (not a learned model — the actual recorded
// player and ball coordinates), for the "実データ再生モード" demo screen.
//
// Source data (not included in this repo — download separately):
//   https://github.com/metrica-sports/sample-data
//   data/Sample_Game_1/Sample_Game_1_RawTrackingData_Home_Team.csv
//   data/Sample_Game_1/Sample_Game_1_RawTrackingData_Away_Team.csv
// Anonymized real match tracking data, used here per the source repo's terms
// (please acknowledge Metrica Sports if you redistribute anything derived from it).
//
// Usage:
//   node scripts/buildReplayData.mjs <home.csv> <away.csv> src/data/replaySample.ts [seconds]
//
// Extracts the first `seconds` (default 300 = 5 min) of Period 1, resampled
// to REPLAY_FPS, keeping every player's literal (x, y) position each frame —
// no positioning model involved, this is a straight playback of real data.

import fs from 'node:fs';

const REPLAY_FPS = 5;
const SOURCE_FPS = 25;

const [, , homePath, awayPath, outPath, secondsArg] = process.argv;
if (!homePath || !awayPath || !outPath) {
  console.error('Usage: node buildReplayData.mjs <home.csv> <away.csv> <output.ts> [seconds]');
  process.exit(1);
}
const seconds = Number(secondsArg) || 300;

function parseTeamCsv(filePath) {
  const text = fs.readFileSync(filePath, 'utf8').replace(/\r/g, '');
  const lines = text.split('\n').filter((l) => l.length > 0);
  const header = lines[2].split(',');

  const playerCols = [];
  for (let i = 3; i < header.length; i++) {
    const name = header[i];
    if (!name) continue;
    playerCols.push({ name, xIdx: i, yIdx: i + 1 });
    i += 1;
  }
  const ballCol = playerCols.find((c) => c.name === 'Ball');
  const players = playerCols.filter((c) => c.name !== 'Ball');

  const rows = [];
  for (let li = 3; li < lines.length; li++) {
    const cols = lines[li].split(',');
    if (Number(cols[0]) !== 1) continue; // Period 1 only
    const bx = Number(cols[ballCol.xIdx]);
    const by = Number(cols[ballCol.yIdx]);
    if (!Number.isFinite(bx) || !Number.isFinite(by)) continue;
    rows.push({
      bx,
      by,
      players: players.map((p) => ({ x: Number(cols[p.xIdx]), y: Number(cols[p.yIdx]) })),
    });
  }
  return rows;
}

function round(n) {
  return Math.round(n * 10000) / 10000;
}

function extractClip(rows) {
  const step = Math.round(SOURCE_FPS / REPLAY_FPS);
  const maxFrames = seconds * REPLAY_FPS;
  const clip = [];

  for (let i = 0; i < rows.length && clip.length < maxFrames; i += step) {
    const row = rows[i];
    const onPitch = row.players.filter((p) => Number.isFinite(p.x) && Number.isFinite(p.y));
    clip.push({
      ball: [round(row.bx), round(row.by)],
      players: onPitch.map((p) => [round(p.x), round(p.y)]),
    });
  }
  return clip;
}

const homeRows = parseTeamCsv(homePath);
const awayRows = parseTeamCsv(awayPath);
const frameCount = Math.min(homeRows.length, awayRows.length);

const homeClip = extractClip(homeRows.slice(0, frameCount));
const awayClip = extractClip(awayRows.slice(0, frameCount));
const n = Math.min(homeClip.length, awayClip.length);

const frames = [];
for (let i = 0; i < n; i++) {
  frames.push({
    ball: homeClip[i].ball,
    home: homeClip[i].players,
    away: awayClip[i].players,
  });
}

console.log(`Extracted ${frames.length} frames (${(frames.length / REPLAY_FPS).toFixed(1)}s at ${REPLAY_FPS}fps)`);

const out = `// Auto-generated by scripts/buildReplayData.mjs from Metrica Sports sample
// tracking data (Sample Game 1, first ${Math.round(frames.length / REPLAY_FPS)}s of Period 1) — see that
// script for the source URL, license notes, and how to regenerate this file.
// These are the literal recorded (x, y) positions from a real match, not a
// model prediction.
export const REPLAY_FPS = ${REPLAY_FPS};

export interface ReplayFrame {
  ball: [number, number];
  home: [number, number][];
  away: [number, number][];
}

export const REPLAY_FRAMES: ReplayFrame[] = ${JSON.stringify(frames)};
`;

fs.writeFileSync(outPath, out, 'utf8');
console.log('Wrote', outPath);
